### PR TITLE
UbuntuColors to theme, added missing titles and rephrase Dialog texts

### LINKED ISSUE #50: In search package dialog, OK buton does not work
As discussed in #33, the ```OK``` button in search package dialog does not work.

Current phone & UT version:
FP2 (2019-W32)

Action:
In Libertine container choose to search for packages. Type some package name (eg. ```curl```) and hit the ```OK``` button.

Current behaviour:
Nothing happens.

Expexted behaviour:
List of packages with desired name is shown (like you hit the ```Enter``` button on keyboard).

### PR DESCRIPTION
**Pull request by cibersheep**
~~Don't merge until I can test this on a device.~~

- UbuntuColors to theme palette counterparts
-  Added missing title to Dialogs
-  Rephrase several Dialogs
-  Fixes #50

### CODE REVIEW

**Comment by cibersheep** [comment]
Tested on device:

Before/after:

imatge
imatge

imatge
imatge

imatge
imatge

**Review by Flohack74 — CHANGES_REQUESTED** [review]
Please include changed pot file...

**Comment by cibersheep** [comment]
True! I forgot, sorry

**Comment by cibersheep** [comment]
I've spent the last hours trying to set up crossbuilder without success.
I can't see the way of rebuilding the pot (and the one in the CI is unchanged)

**Comment by Flohack74** [comment]
Hmm interesting. We need to solve this, I am 1000% sure the new strings will not be in :)

**Comment by cibersheep** [comment]
From my side this is because I couldn't build the project or trigger the cmake. I edit the qml and push it. From CI side... I don't know, I thought it should cmake them... Do we need a second trigger?

Maybe today I will try to install the crossbuilder again on a 18.04 installation, somehow

**Comment by Flohack74** [comment]
The CI might build a pot file temporarily, but it is not supposed to commit it to the repo. Thats simply not what a CI should do ^^ - so if you see it in the CI logs, its deleted afterwards again. A code commit should be atomic change that can be replayed and reverted, so also form that point of view you cannot do a 2-step-commit for a localization issue.

**Comment by cibersheep** [comment]
~~Mmmm... I'm unable to set crossbuilder correctly. I get different errors I cannot solve or find a solution for. Sorry~~

StubbornSheep reporting back. Snap lxd helped me here. Weeee

I have build the project but pot file looks unmodified. Do I have to do something special?

Update: Ah, no:
```
libertine$ crossbuilder build
LXD container libertine-usdk-16-04-amd64-armhf-dev already exists.

Installing armhf (host amd64) build dependencies for libertine in container libertine-usdk-16-04-amd64-armhf-dev.
Installing armhf build dependencies for libertine in container libertine-usdk-16-04-amd64-armhf-dev.
Hit:1 http://archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://ports.ubuntu.com/ubuntu-ports xenial InRelease                                   
[...]
Get:12 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [780 kB]
Fetched 2434 kB in 2s (1016 kB/s)                          
Reading package lists... Done
sh: 1: mk-build-deps: not found     
```

**Review by Flohack74 — APPROVED** [review]

**Pull request merged**
