### PR TITLE
think this is the correct place to add .lower(). ... hopefully

### PR DESCRIPTION
**Pull request by padraic7a**
Hi, not a real pull request  I am doing this to see if the CI will build the deb, and then to install it to see if it does what I think it should. I hope this isn't wasting anyone's time. 

If a pull request for this purpose isn't kosher please let me know.

### CODE REVIEW

**Comment by Flohack74** [comment]
Sorry to say but CI did not see this PR. I also dont why...

**Comment by padraic7a** [comment]
Yeah,I figured that was the case after I made the pull request.

Is the CI set to look at this specific repo at all? 

I don't have any experience creating debs. @Flohack74 is there anywhere I could raise the CI issue or get advice at this stage?

**Comment by Flohack74** [comment]
It is set up https://ci.ubports.com/blue/organizations/jenkins/libertine/activity and it worked until recently it seems. Need to talk with @mariogrip :)

**Comment by padraic7a** [comment]
Actually the python code isn't the correct place for this fix. Closing.

**Comment by UniversalSuperBox** [comment]
To the future traveller who gets here from #45: he meant #44 :)

**Pull request closed without merging**
